version: '3.8'

services:
  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/postgres
      REDIS_ADDR: redis:6379
    networks:
      - app-network
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      PGUSER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  pgdata:
networks:
  app-network: